#!/usr/bin/env bash


proxy="${proxy:-}"
noproxy="${noproxy:-}"
out="${out:-}"
url="${url:-}"
HELP="${HELP:-}"
while [ $# -gt 0 ]; do
    case "$1" in
        --proxy|-x)
            proxy="$2"
            shift
            ;;
        --noproxy|--no-proxy)
            noproxy="$2"
            shift
            ;;
        --out|-o)
            out="$2"
            shift
            ;;
        --help|-h)
            HELP=1
            ;;
        --url|-fSL|-f#SL)
            url="$2"
            shift
            ;;
        --*)
            echo "Illegal option $1"
            ;;
    esac
    shift $(( $# > 0 ? 1 : 0 ))
done

aria2c_opts_array=()
if [ -n "${proxy}" ] ; then
    aria2c_opts_array+=("--all-proxy ${proxy}")
fi

if [ -n "${proxy}" ] ; then
    aria2c_opts_array+=("--no-proxy ${noproxy}")
fi
if [ -n "${out}" ] ; then
    aria2c_opts_array+=("-o ${out}")
fi

if [ "$HELP" = "1" ]; then
(
    echo "dl"
    echo "--proxy               proxy"
    echo "--noproxy             noproxy"
    echo "--output|-o           outputfile"
    echo "--url|-fsL            url"
    echo "dl -fSL https://mirrors.huaweicloud.com/ubuntu-cloud-images/noble/current/noble-server-cloudimg-amd64.img"

)
exit 0;
fi

set -x;
aria2c ${aria2c_opts_array[*]} --split=32 --max-concurrent-downloads=32 --max-connection-per-server=16 "${url}"



# aria2c -h#all |grep proxy
#                               connection to HTTP/FTP/proxy server. After the
#                               users behind proxy server which disables resume.
#  --http-proxy=PROXY           Use a proxy server for HTTP. To override a
#                               previously defined proxy, use "".
#                               See also the --all-proxy option.
#  --https-proxy=PROXY          Use a proxy server for HTTPS. To override a 
#                               previously defined proxy, use "".
#                               See also the --all-proxy option.
#  --ftp-proxy=PROXY            Use a proxy server for FTP. To override a 
#                               previously defined proxy, use "".
#                               See also the --all-proxy option.
#  --all-proxy=PROXY            Use a proxy server for all protocols. To override
#                               a previously defined proxy, use "".
#                               proxy server for a particular protocol using the
#                               --http-proxy, --https-proxy and --ftp-proxy
#  --no-proxy=DOMAINS           Specify comma separated hostnames, domains or
#                               proxy should not be used.
#  --proxy-method=METHOD        Set the method to use in proxy request.
#  --http-proxy-user=USER       Set user for --http-proxy.
#  --http-proxy-passwd=PASSWD   Set password for --http-proxy.
#  --https-proxy-user=USER      Set user for --https-proxy.
#  --https-proxy-passwd=PASSWD  Set password for --https-proxy.
#  --ftp-proxy-user=USER        Set user for --ftp-proxy.
#  --ftp-proxy-passwd=PASSWD    Set password for --ftp-proxy.
#  --all-proxy-user=USER        Set user for --all-proxy.
#  --all-proxy-passwd=PASSWD    Set password for --all-proxy.
